[package]
name = "my_clock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-console = "0.2"
yew = "0.19.3"
js-sys = "0.3.55"
wasm-bindgen = "0.2"
gloo-timers = "0.2"